### ISSUE TITLE
有對應於思源宋/明體的版本嗎?

### ISSUE THREAD

**Issue by roytam1** [tamcy/CYanHeiHK#12]
https://github.com/adobe-fonts/source-han-serif

**Comment by tamcy** [comment]
目前沒有。暫不考慮。

思源宋現時缺乏HKSCS支援，太多香港常用字沒有包括，有包括的也大多採用CN源字形，換言之如果要做就要先補足這些字。另外，來源不提供做好最幼和最粗兩款再生成其他字重的方案，即是要逐個字重分開做。就算做了出來，由於很多字與思源推出的香港版重疊，最終還是會用回思源香港版的字形，所花時間似乎並不值得。何況這個計劃的目的是希望盡量使用思源本身的字形，做出一個平衡標準與實用性、較適用於香港地區的字體。造字、補字非本計劃的主力。考慮到投放的心力、時間、結果和本計劃的性質，現時暫不考慮開展一個對應香港的思源宋體。

個人而言，希望到2.000版時有時間處理。
