### ISSUE TITLE
巽等字建議直接採用中國寫法。 

### ISSUE THREAD

**Issue by hfhchan** [tamcy/CYanHeiHK#4]
巽等字建議採用中國寫法。 
蒙納宋與儷宋均帶夠。

**Comment by tamcy** [comment]
這個我考慮看看（其實我覺得沒鈎版本也不是太難看，不過既然像七、流等字也會改用有鈎版本，不如這個也改用好了。不過選字要花點時間改不能單純用remap解決）

**Comment by tamcy** [comment]
Fixed in v1.008.
