### ISSUE TITLE
柒等字建議直接採用中國寫法帶夠

### ISSUE THREAD

**Issue by hfhchan** [tamcy/CYanHeiHK#5]
柒等字建議直接採用中國寫法。

蒙納宋 華康儷宋均帶夠

中文界面諮詢委員會工作小組會議 第 7 次會議決定改為有鉤:
 http://www.ogcio.gov.hk/tc/business/tech_promotion/ccli/cliac/doc/Mins_7th_WG-CLIAC_meeting.pdf

**Comment by tamcy** [comment]
謝謝通知，下一版會改。

**Comment by tamcy** [comment]
Fixed in v1.008.
