### ISSUE TITLE
U+2018 U+2019 U+201C U+201D 採用比例(proportional)符號

### ISSUE THREAD

**Issue by hfhchan** [tamcy/CYanHeiHK#7]
繁體中文環境下，理論上不應該使用歐文引號「＂」，U+2018 U+2019 U+201C U+201D 多見於英文。

建議改成日文／韓文寬度：
![image](https://cloud.githubusercontent.com/assets/8191296/21306378/99917a96-c60b-11e6-9a34-178fc375f853.png)

**Comment by RedBug312** [comment]
+1 補充原思源黑體 [Issue 解釋](https://github.com/googlei18n/noto-cjk/issues/5)
雖然答應在 Version 2.000 更新但尚未實作

**Comment by tamcy** [comment]
我明白這個改動是想解決看英文時「’」會變成全形的問題。但是，在中文環境如果真要看到/用到‘’“”時，我還是會期望這些符號顯示為全形。結果還是順得哥情失嫂意。

更最重要的是，如果西歐引號預設為全形，尚有簡單方法可以解決英文’的問題（如 stylesheet 先定義 Latin 字體、Word 中英文用不同字體。而其實這是很正常的做法）。反之當字體西歐引號預設為半形，要調用全形glyphs就沒那麼容易。既然 upstream 考慮改，我這邊且按兵不動好了。
