### ISSUE TITLE
建議區分「日」和「曰」部件

### ISSUE THREAD

**Issue by SyaoranHinata** [tamcy/CYanHeiHK#8]
《常用字字形表》和《香港電腦漢字參考字形》都有區分，這個區分也不會突兀 (可以參考蘋果的蘋方港版) 。

**Comment by SyaoranHinata** [comment]
補充資料：
http://www.ogcio.gov.hk/tc/business/tech_promotion/ccli/cliac/doc/char2014-09.pdf
第6頁有說：
5.5 字義變化（視作兩者的區別）：
鑒於部件「日」（部件碼：0_2F47）、「曰」（部件碼：0_2F48）及「⺜」（部件碼：1_2E9C）內部橫的連線會導致字義變化，香港字形對此三個部件進行了區分，即，對於「日」，中間橫筆觸及左右的豎筆 ；對於「曰」，中間橫筆只觸及左邊的豎筆；對於「⺜」，中間橫筆不觸及左右的豎筆。

**Comment by SyaoranHinata** [comment]
![image](https://cloud.githubusercontent.com/assets/8178284/21362354/f775c974-c722-11e6-8410-b96028cdca46.png)

**Comment by tamcy** [comment]
我知道這個區分，惟傳統黑體也沒有此區別，而且此區分不能單靠更改對映達成而須更改設計，因此不作考慮。
